# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_left
    snippet: studio-rpc-usb-uart
    artifact-name: crkbd_zmk_left_with_studio
  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_DISPLAY=n
    snippet: studio-rpc-usb-uart
    artifact-name: crkbd_zmk_left_with_studio_no_display
  - board: nice_nano_v2
    shield: corne_right
    artifact-name: crkbd_zmk_right_with_studio
  - board: nice_nano_v2
    shield: corne_left
    snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=CorneChoc
    cmake-args: -DDZMK_CONFIG=./config/cornechoc.conf
    artifact-name: chocoflan_zmk_left_with_studio
  - board: nice_nano_v2
    shield: corne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DDZMK_CONFIG=./config/corneglp.conf
    artifact-name: corne_glp_zmk_left_with_studio
  - board: nice_nano_v2
    shield: settings_reset
